/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "psoasfqzcbpqjgatcgfh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzb2FzZnF6Y2JwcWpnYXRjZ2ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4NzExNDEsImV4cCI6MjA4ODQ0NzE0MX0.i_RntOlOW7mq8PO0k233G4nPdQiO-biYi-MYpzqUF-A"